# Automatically generated by Honest Code
# Do not edit this file as it will be overwritten

  @rock
Feature: camion
  rocker
  buy a truck to be happy

  Scenario: comprar camion
    Given a rocker
    When I buy a truck
    And I buy a truck
      |  |
      |  |
    Then i am happy
